<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-07-11T13:49:03 EET" name="Default suite" finished-at="2025-07-11T13:49:31 EET" duration-ms="27507">
    <groups>
    </groups>
    <test started-at="2025-07-11T13:49:03 EET" name="Default test" finished-at="2025-07-11T13:49:31 EET" duration-ms="27507">
      <class name="LoginPage.myTestCases">
        <test-method is-config="true" signature="mySetup()[pri:0, instance:LoginPage.myTestCases@d3957fe]" started-at="2025-07-11T13:49:03 EET" name="mySetup" finished-at="2025-07-11T13:49:06 EET" duration-ms="2658" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mySetup -->
        <test-method signature="Signup()[pri:1, instance:LoginPage.myTestCases@d3957fe]" started-at="2025-07-11T13:49:06 EET" name="Signup" finished-at="2025-07-11T13:49:21 EET" duration-ms="15311" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Signup -->
        <test-method signature="Logout()[pri:2, instance:LoginPage.myTestCases@d3957fe]" started-at="2025-07-11T13:49:21 EET" name="Logout" finished-at="2025-07-11T13:49:26 EET" duration-ms="4929" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Logout -->
        <test-method signature="Login()[pri:3, instance:LoginPage.myTestCases@d3957fe]" started-at="2025-07-11T13:49:26 EET" name="Login" finished-at="2025-07-11T13:49:27 EET" duration-ms="1029" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Login -->
        <test-method signature="AddtoCart()[pri:4, instance:LoginPage.myTestCases@d3957fe]" started-at="2025-07-11T13:49:27 EET" name="AddtoCart" finished-at="2025-07-11T13:49:31 EET" duration-ms="3555" status="FAIL">
          <exception class="java.lang.IndexOutOfBoundsException">
            <message>
              <![CDATA[Index 1 out of bounds for length 0]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 0
at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
at java.base/java.util.Objects.checkIndex(Objects.java:385)
at java.base/java.util.ArrayList.get(ArrayList.java:427)
at LoginPage.myTestCases.AddtoCart(myTestCases.java:172)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IndexOutOfBoundsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- AddtoCart -->
      </class> <!-- LoginPage.myTestCases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
